config/routes.rb
Rails.application.routes.draw do

  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  namespace :api, defaults: { format: :json } do
    namespace :v1 do 
      resources :posts, only: [:create, :index] do
        resources :comments, only: [:create, :index]
      end
    end
  end

  devise_for :users

  default_url_options :host => 'localhost'

  devise_scope :user do
    # write all your routes inside this block
    root 'users#index'
    resources :users, only: [:index, :show] do
      resources :posts, only: [:index, :new, :create, :show]
    end
  
    resources :posts do
      resources :comments, only: [:create, :destroy]
      resources :likes, only: [:create]
    end
  end
  
  end

app/models/user.rb
class User < ApplicationRecord
  include Devise::JWT::RevocationStrategies::JTIMatcher
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable,
         :jwt_authenticatable, jwt_revocation_strategy: self
  validates :name, presence: true
  validates :posts_counter, numericality: { greater_than_or_equal_to: 0 }
  has_many :posts
  has_many :likes, through: :posts
  has_many :comments, through: :posts

  def last_recent_posts
    posts.includes(:comments).last(3)
  end
end

app/models/users.rb
class Users < ApplicationRecord
  has_many :posts
  has_many :likes, through: :posts
  has_many :comments, through: :posts
  def last_recent_posts
    posts.last(3)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.order(created_at: :asc)
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.last_recent_posts
  end
end

app/helpers/api/v1/users_helper.rb
module Api::V1::UsersHelper
end

app/views/users/_not_logged.html.erb
<h1 class="notlogged-header"> Welcome to BlogApp </h1>
<div class="notlooged-btn-container">
<%= link_to "Log in", new_user_session_path, class:"notlogged-btn signin" %>
<%= link_to "Create account", new_user_registration_path, class:"notlogged-btn create" %>
</div>

app/views/users/index.html.erb
    <%if user_signed_in?%>


<div class="add-post-btn d-flex">
<%= link_to "Add a new post", new_user_post_path(current_user.id) %>
<%= button_to "Logout", destroy_user_session_path, :method => :delete,
  class:"logout-btn" %>
</div>

<% @users.each do |user| %>
<div class="user-container d-flex">
  <div class="user-img">
    <%= image_tag("user/user_logo.png", width:'100%', height:'100%') %>
  </div>
  <div class="user-data d-flex">
    <h2><a href="/users/<%=user.id%>"><%= user.name %></a></h2>
    <p>
      <a href="/users/<%=user.id%>/posts/"> Number of posts: <%= user.posts_counter %></a>
    </p>
  </div>
</div>
<%end %>

    <%else%>
     <%= render partial: "not_logged"%>
    <%end %>

app/views/users/show.html.erb
<div class="user-container d-flex">
  <div class="user-img">
    <%= image_tag("user/user_logo.png", width:'100%', height:'100%') %>
  </div>
  <div class="user-data d-flex">
    <h2><%= @user.name %></h2>
    <p>
      <a href="/users/<%=@user.id%>/posts/">Number of posts: <%= @user.posts_counter %></a>
    </p>
  </div>
</div>

<div class="bio-data">
  <h2 class="bio-span">Bio</h2>
  <p class="bio-body"><%= @user.bio %></p>
</div>

<div class="recent-posts">
  <% @posts.each do |post| %>
  <div class="recent-posts posts-details d-flex">
    <h2>
     <a href="/users/<%=@user.id%>/posts/<%=post.id%>"><%= post.title%></a>
    </h2>
    <p class="posts-body"><%= post.text %></p>
    <p class="posts-counters">Comments: <%= post.comments_counter %>, Likes: <%= post.likes_counter %></p>
  </div>
  <%end %>
</div>

<div class="see-posts d-flex">
  <a href="/users/<%=@user.id%>/posts/">See all posts</a>
</div>