config/routes.rb
Rails.application.routes.draw do

  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  namespace :api, defaults: { format: :json } do
    namespace :v1 do 
      resources :posts, only: [:create, :index] do
        resources :comments, only: [:create, :index]
      end
    end
  end

  devise_for :users

  default_url_options :host => 'localhost'

  devise_scope :user do
    # write all your routes inside this block
    root 'users#index'
    resources :users, only: [:index, :show] do
      resources :posts, only: [:index, :new, :create, :show]
    end
  
    resources :posts do
      resources :comments, only: [:create, :destroy]
      resources :likes, only: [:create]
    end
  end
  
  end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, :likes_counter, numericality: { greater_than_or_equal_to: 0 }
  belongs_to :user
  has_many :likes, dependent: :delete_all
  has_many :comments, dependent: :delete_all

  def update_post_counter
    user.increment!(:posts_counter)
  end

  def recent_comments
    comments.last(5)
  end
end

app/models/posts.rb
class Posts < ApplicationRecord
  belongs_to :users
  has_many :likes, :comments

  def update_post_counter
    users.posts_counter += 1
  end

  def recent_comments
    comments.last(5)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < Api::V1::ApiController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @posts = Post.all
    render json: @posts
  end

  def create
    @post = current_user.posts.new(post_params)
    @post.comments_counter = 0
    @post.likes_counter = 0
    if @post.save
      render json: { status: 201, message: 'Comment created successfully!' }
    else
      render json: { errors: @post.errors }, status: 422
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments)
  end

  def show
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
    @like = Like.where(user_id: current_user.id, post_id: params[:id]).exists?
  end

  def new
    @post = Post.new
  end

  def create
    new_post = current_user.posts.new(post_params)
    new_post.likes_counter = 0
    new_post.comments_counter = 0
    new_post.update_post_counter
    respond_to do |format|
      format.html do
        if new_post.save
          redirect_to "/users/#{new_post.user.id}/posts/", notice: 'Success!'
        else
          render :new, alert: 'Error occured!'
        end
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    @user = User.find(@post.user_id)
    @user.posts_counter -= 1
    @user.save
    redirect_to("/users/#{current_user.id}")
    flash[:success] = 'Post was destroyed!'
  end

  private

  def post_params
    params.require(:data).permit(:title, :text)
  end
end

app/views/posts/_create_comment.html.erb
<%= form_with url: "/posts/#{@post.id}/comments", scope: :comment do |form| %>
<div class="comment-container d-flex">
	<%= form.text_area :text, placeholder: "Comment something here...", rows: 14, required: true %>
	<%= form.submit "Comment", class: "submit-btn comment-btn" %>
  </div>
<% end %>

app/views/posts/_create_like.html.erb
<%= form_with url: "/posts/#{@post.id}/likes", scope: :like do |form| %>
  <% if @like%>
  <button class="post-stat-btns like-btn liked" disabled>👍🏻</button>
  <%else%>
  <%= form.submit "👍🏻", class: "post-stat-btns like-btn not-liked"%>
  <%end%>
<% end %>

app/views/posts/_delete_post.html.erb
<% if can? :destroy, @post%>
    <%=button_to 'Delete', {:controller => :posts, :action => 'destroy', :id => @post.id}, :method => :delete%> 
<% end %>

app/views/posts/index.html.erb
<section class="user-container d-flex">
  <div class="user-img">
    <%= image_tag("user/user_logo.png", width:'100%', height:'100%') %>
  </div>
  <div class="user-data d-flex">
    <h2><%= @user.name %></h2>
    <p>Number of posts: <%= @user.posts_counter %></p>
  </div>
</section>

<% @posts.each do |post| %>
<section class="comments-section">
  <div class="posts-container">
    <div class="posts-details d-flex">
      <h2 class="posts-id"><a href="/users/<%= @user.id %>/posts/<%=post.id%>"><%= post.title %></a></h2>
      <p class="posts-body"><%= post.text %></p>
      <p class="posts-counters">Comments: <%= post.comments_counter %>, Likes: <%= post.likes_counter %></p>
    <% unless post.recent_comments.empty? %>
    <div class="posts-comments d-flex">
    <% post.recent_comments.each do |comment| %>
      <p class="users-comment">
       <a href = <%=user_path(comment.user.id)%>><%= comment.user.name %></a>: <%= comment.text %>
      </p>
    <% end %>
    </div>
    <% end %>
    </div>
  </div>
</section>
<%end%>

app/views/posts/new.html.erb
<h1 class ="post-create-header">Create a post</h1>
<%= form_with url: user_posts_path, scope: :data do |form| %>
<div class="form-container d-flex">
	<section class="title-section from-input d-flex">
		<%= form.label :title, "Title", class: "label" %>
		<%= form.text_field :title, placeholder: "Title", required: true %>
	</section>
	<section class="body-section from-input d-flex">
		<%= form.text_area :text, placeholder: "Type here...", rows: 14, required: true %>
	</section>
	<%= form.submit "Post", class: "submit-btn" %>
  </div>
<% end %>

app/views/posts/show.html.erb
<section class="posts-section">
  <div class="post-header d-flex">
    <h2 class="post-title"><%= @post.title %></h2>
    <div class="post-data-counter d-flex">
    <button class="post-stat-btns unclickble">Comments: <%= @post.comments_counter %></button>
    <button class="post-stat-btns unclickble">Likes: <%= @post.likes_counter %></button>
    <%= render partial: "create_like", local: @post %>
    </div>
  </div>
  <div class="detroy-text-container d-flex">
  <p class="post-data-counter">
    <%= @post.text %>
  </p>
  <%= render partial: "delete_post", local: @post %>
  </div>
</section>


<section class="posts-section-comments d-flex">
<% unless @post.comments.empty? %>
<% @post.comments.each do |comment| %>
      <p class="users-comment">
      <a href = <%=user_path(comment.user.id)%>><%= comment.user.name %></a>: <%= comment.text %>
      </p>
      <% if can? :destroy, comment %>
        <%=button_to 'delete', post_comment_path(post_id: @post.id ,id: comment.id), :method => :delete%> 
      <% end %>
<% end %>
<% end %>
<%= render partial: "create_comment", local: { post: @post, like: @like } %>
</section>
    